version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/subscriptions?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true

    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.27
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=09092001
      - MYSQL_DATABASE=subscriptions
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver

networks:
  springmysql-net: